import { Link } from 'react-router-dom';
import { ChevronRight, Home as HomeIcon, Wheat, Heart, Leaf, Truck, ShieldCheck, Users } from 'lucide-react';

export default function About() {
  const values = [{ icon: Leaf, title: '100% Organic', desc: 'All our products are sourced from certified organic farms with no chemicals or pesticides.' }, { icon: ShieldCheck, title: 'Quality First', desc: 'Every product goes through rigorous quality checks before reaching your doorstep.' }, { icon: Heart, title: 'Customer Love', desc: 'We treat every customer like family. Your satisfaction is our top priority.' }, { icon: Truck, title: 'Fast Delivery', desc: 'We deliver across Pakistan with free shipping on orders above Rs. 8000.' }];
  const stats = [{ value: '15,000+', label: 'Happy Customers' }, { value: '50+', label: 'Products' }, { value: '12+', label: 'Categories' }, { value: '4.8★', label: 'Average Rating' }];
  return (
    <div className="animate-fade-in">
      <div className="bg-gray-50 border-b border-gray-100"><div className="container-app py-3"><div className="flex items-center gap-1.5 text-sm text-gray-500"><Link to="/" className="hover:text-primary-600 flex items-center gap-1"><HomeIcon size={14} /> Home</Link><ChevronRight size={14} /><span className="text-gray-900 font-medium">About</span></div></div></div>
      <section className="relative h-[300px] lg:h-[400px] overflow-hidden bg-primary-950"><img src="https://images.pexels.com/photos/5234982/pexels-photo-5234982.jpeg" alt="Organic foods" className="absolute inset-0 w-full h-full object-cover opacity-40" /><div className="absolute inset-0 flex items-center justify-center"><div className="text-center max-w-2xl px-4"><Wheat className="text-primary-300 mx-auto mb-3" size={40} /><h1 className="font-display text-3xl lg:text-5xl font-bold text-white mb-3">About Ahmad Herbals</h1><p className="text-primary-100 text-lg">Bringing the authentic taste and heritage of Punjab to your home with premium organic foods.</p></div></div></section>
      <section className="py-12 lg:py-16"><div className="container-app max-w-4xl"><h2 className="font-display text-2xl lg:text-3xl font-bold text-gray-900 mb-4">Our Story</h2><div className="space-y-4 text-gray-700 leading-relaxed"><p>Ahmad Herbals was born from a simple idea: to bring the authentic, traditional flavors of Punjab to modern households. In an era where processed and chemically-treated foods have become the norm, we wanted to go back to our roots.</p><p>Our journey began in the heart of Punjab, where we source the finest grains, dry fruits, and spices directly from local farmers. We work closely with our farming partners to ensure every product meets our strict quality standards.</p><p>Today, we offer over 50 products across 12 categories — from multi-grain flours and premium dry fruits to pure organic honey and Himalayan pink salt.</p></div></div></section>
      <section className="py-8 bg-primary-950"><div className="container-app"><div className="grid grid-cols-2 lg:grid-cols-4 gap-6">{stats.map((stat, i) => <div key={i} className="text-center"><p className="font-display text-3xl lg:text-4xl font-bold text-white">{stat.value}</p><p className="text-sm text-primary-300 mt-1">{stat.label}</p></div>)}</div></div></section>
      <section className="py-12 lg:py-16"><div className="container-app"><h2 className="font-display text-2xl lg:text-3xl font-bold text-gray-900 text-center mb-2">Our Values</h2><p className="text-gray-500 text-center mb-10">What we stand for</p><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">{values.map((val, i) => <div key={i} className="card p-6 text-center"><div className="w-14 h-14 rounded-xl bg-primary-50 flex items-center justify-center mx-auto mb-4"><val.icon className="text-primary-600" size={28} /></div><h3 className="font-display text-lg font-semibold text-gray-900 mb-2">{val.title}</h3><p className="text-sm text-gray-600 leading-relaxed">{val.desc}</p></div>)}</div></div></section>
      <section className="py-12"><div className="container-app"><div className="bg-primary-50 rounded-2xl p-8 lg:p-12 text-center"><Users className="text-primary-600 mx-auto mb-4" size={40} /><h2 className="font-display text-2xl lg:text-3xl font-bold text-gray-900 mb-3">Join Our Family</h2><p className="text-gray-600 mb-6 max-w-md mx-auto">Experience the authentic taste of Punjab with our premium organic products.</p><Link to="/shop" className="btn-primary">Start Shopping</Link></div></div></section>
    </div>
  );
}
